function [compA, compB, compC] = importEDXFile(filename, startRow, endRow)
%IMPORTEDXFILE Import EDX data from a text file as column vectors.
%   [COMPA, COMPB, COMPC] = IMPORTEDXFILE(FILENAME) Reads data from
%   text file FILENAME for the default selection.
%
%   [COMPA, COMPB, COMPC] = IMPORTEDXFILE(FILENAME, STARTROW, ENDROW)
%   Reads data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   [compA, compB, compC] = importfile('MnFeCoO-EDX',1, 342);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/06/08 13:14:07

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, ...
    'Delimiter', delimiter, ...
    'HeaderLines', startRow(1)-1, ...
    'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, ...
        endRow(block)-startRow(block)+1, ...
        'Delimiter', delimiter, ...
        'HeaderLines', startRow(block)-1, ...
        'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Allocate imported array to column variable names
compA = dataArray{:, 1};
compB = dataArray{:, 2};
compC = dataArray{:, 3};


