%importXRDFile imports numeric data from a text file as column vectors.
%   [angle, intensity] = importXRDFile(filename) Reads data from text file
%   FILENAME for the default selection.
%
% Example:
%   [VarName1,VarName2] = importXRDFile('55_1-11_Helge batch_-40.50_-4.50_2.xy',1, 1752);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/06/07 10:29:05

function [angle, intensity] = importXRDFile(filename, startRow, endRow)
%% Initialize variables.
delimiter = ' ';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Format string for each line of text:
%   column1 (angle): double (%f)
%	column2 (intensity): double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Allocate imported array to column variable names
angle = dataArray{:, 1};
intensity = dataArray{:, 2};


