function [hbuttonScaleSqrt, hbuttonScaleLog, hbuttonScaleNone, hbuttonSave, fSpecButtons, fSpecPlot] = openSpecFigs()
%UNTITLED6 Summary of this function goes here
%   Detailed explanation goes here

fSpecButtons = figure('Visible', 'off', ...
    'Units', 'Normalized', ...
    'Position', [0.03 0.03 0.45 0.45]);
fSpecPlot = figure('Visible', 'off', ...
    'Units', 'Normalized', ...
    'Position', [0.52 0.03 0.45 0.45]);

% set background to white
figure(fSpecButtons);
set(gcf, 'color', 'w');
figure(fSpecPlot);
set(gcf, 'color', 'w');

% set tabs in button window
tabsSpec = uitabgroup('Parent', fSpecButtons);
tabStyle = uitab('Parent', tabsSpec, 'Title', 'Plot style');
tabSelect = uitab('Parent', tabsSpec, 'Title', 'Select points');



%% components

leftColOffset = 0.05;
topRowOffset = 0.7;
buttonWidth = 0.2;
buttonHeight = 0.05;
textSpacingVert = 0.1;

hbuttonScaleSqrt = uicontrol('Parent', tabStyle, ...
    'Style', 'pushbutton', ...
    'String', 'Scale sq. rt.', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset topRowOffset buttonWidth buttonHeight]);
hbuttonScaleLog = uicontrol('Parent', tabStyle, ...
    'Style', 'pushbutton', ...
    'String', 'Scale log', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset (topRowOffset - textSpacingVert) ...
    buttonWidth buttonHeight]);
hbuttonScaleNone = uicontrol('Parent', tabStyle, ...
    'Style', 'pushbutton', ...
    'String', 'No scale', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset (topRowOffset - 2 * textSpacingVert) ...
    buttonWidth buttonHeight]);

hbuttonSave = uicontrol('Parent', tabSelect, ...
    'Style', 'pushbutton', ...
    'String', 'Save points', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset topRowOffset buttonWidth buttonHeight]);

%% make windows visible

fSpecButtons.Visible = 'on';
fSpecPlot.Visible = 'on';

end

