function ECHandles = openECFigs()
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here

% create EC windows
ECHandles.fECButtons = figure(...
    'Visible', 'off', ...
    'Units', 'Normalized', ...
    'Position', [0.3 0.7 0.4 0.2], ...
    'Name', 'EC Data Plot Settings');
ECHandles.fECPlot = figure(...
    'Visible', 'off', ...
    'Units', 'Normalized', ...
    'Position', [0.3 0.03 0.45 0.45], ...
    'Name', 'EC Data Plot');

% set background to white
figure(ECHandles.fECButtons);
set(gcf, 'color', 'w');
figure(ECHandles.fECPlot);
set(gcf, 'color', 'w');

% set tabs in button window
tabsEC = uitabgroup('Parent', ECHandles.fECButtons);
tabStyle = uitab('Parent', tabsEC, 'Title', 'Plot style');
tabSelect = uitab('Parent', tabsEC, 'Title', 'Select plot');
tabAnalyze = uitab('Parent', tabsEC, 'Title', 'Analyze plot');
tabPostProcess = uitab('Parent', tabsEC, 'Title', 'Post-process');

%% components

topRowOffset = 0.8;
buttonWidth = 0.3;
buttonHeight = 0.2;
textSpacingVert = 0.2;
%midColOffset = 0.5 - buttonWidth / 2;
leftColOffset = 0.1;
rightColOffset = 0.5;
editHeight = buttonHeight;
editWidth = buttonWidth / 2;
rowSpace = 0.2;

% analyze tab

ECHandles.buttonLowerSlope = uicontrol('Parent', tabAnalyze, ...
    'Style', 'pushbutton', ...
    'String', 'Fit lower slope', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset topRowOffset buttonWidth buttonHeight]);
ECHandles.textLowerSlope = uicontrol('Parent', tabAnalyze, ...
    'Style', 'text', ...
    'String', '', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset (topRowOffset - rowSpace)...
    buttonWidth buttonHeight]);
ECHandles.buttonHigherSlope = uicontrol('Parent', tabAnalyze, ...
    'Style', 'pushbutton', ...
    'String', 'Fit higher slope', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset (topRowOffset - rowSpace * 2) ...
    buttonWidth buttonHeight]);
ECHandles.textHigherSlope = uicontrol('Parent', tabAnalyze, ...
    'Style', 'text', ...
    'String', '', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset (topRowOffset - rowSpace * 3) ...
    buttonWidth buttonHeight]);

ECHandles.buttonTafel = uicontrol('Parent', tabAnalyze, ...
    'Style', 'pushbutton', ...
    'String', 'Calc. Tafel slope', ...
    'Units', 'Normalized', ...
    'Position', [rightColOffset topRowOffset buttonWidth buttonHeight]);
ECHandles.textTafel = uicontrol('Parent', tabAnalyze, ...
    'Style', 'text', ...
    'String', '', ...
    'Units', 'Normalized', ...
    'Position', [rightColOffset (topRowOffset - rowSpace)...
    buttonWidth buttonHeight]);
ECHandles.buttonOnsetPot = uicontrol('Parent', tabAnalyze, ...
    'Style', 'pushbutton', ...
    'String', 'Calc. onset potential', ...
    'Units', 'Normalized', ...
    'Position', [rightColOffset (topRowOffset - rowSpace * 2) ...
    buttonWidth buttonHeight]);
ECHandles.textOnsetPot = uicontrol('Parent', tabAnalyze, ...
    'Style', 'text', ...
    'String', '', ...
    'Units', 'Normalized', ...
    'Position', [rightColOffset (topRowOffset - rowSpace * 3) ...
    buttonWidth buttonHeight]);
ECHandles.buttonReset = uicontrol('Parent', tabAnalyze, ...
    'Style', 'pushbutton', ...
    'String', 'Reset values', ...
    'Units', 'Normalized', ...
    'Position', [rightColOffset (topRowOffset - rowSpace * 4) ...
    buttonWidth buttonHeight]);

% select plot tab

ECHandles.textSelect = uicontrol('Parent', tabSelect, ...
    'Style', 'text', ...
    'String', 'Composition', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset topRowOffset buttonWidth buttonHeight]);
ECHandles.editSelect = uicontrol('Parent', tabSelect, ...
    'Style', 'edit', ...
    'String', '0', ...
    'Units', 'Normalized', ...
    'Position', [(leftColOffset + (buttonWidth - editWidth) / 2) (topRowOffset - buttonHeight + 0.05) ...
    editWidth editHeight]);
ECHandles.buttonIncrease = uicontrol('Parent', tabSelect, ...
    'Style', 'pushbutton', ...
    'String', 'Increase only', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset (topRowOffset - buttonHeight - textSpacingVert) ...
    buttonWidth buttonHeight]);
ECHandles.buttonDecrease = uicontrol('Parent', tabSelect, ...
    'Style', 'pushbutton', ...
    'String', 'Decrease only', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset (topRowOffset - buttonHeight - 2 * textSpacingVert) ...
    buttonWidth buttonHeight]);
ECHandles.buttonBoth = uicontrol('Parent', tabSelect, ...
    'Style', 'pushbutton', ...
    'String', 'Both', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset (topRowOffset - buttonHeight - 3 * textSpacingVert) ...
    buttonWidth buttonHeight]);

% style tab

ECHandles.textOffset = uicontrol('Parent', tabStyle, ...
    'Style', 'text', ...
    'String', 'Offset', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset topRowOffset buttonWidth buttonHeight], ...
    'UserData', 1);
ECHandles.editOffset = uicontrol('Parent', tabStyle, ...
    'Style', 'edit', ...
    'String', '1', ...
    'UserData', 1, ...
    'Units', 'Normalized', ...
    'Position', [(leftColOffset + (buttonWidth - editWidth) / 2) (topRowOffset - buttonHeight + 0.05) ...
    editWidth editHeight]);

% post process tab

ECHandles.buttonPrint = uicontrol('Parent', tabPostProcess, ...
    'Style', 'pushbutton', ...
    'String', 'Print analysis', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset topRowOffset buttonWidth buttonHeight]);

ECHandles.buttonPlotTern = uicontrol('Parent', tabPostProcess, ...
    'Style', 'pushbutton', ...
    'String', 'Plot Tafel/Onset data', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset (topRowOffset - rowSpace) ...
    buttonWidth buttonHeight]);

%% make windows visible

fig = ECHandles.fECButtons;
fig.Visible = 'on';
fig = ECHandles.fECPlot;
fig.Visible = 'on';

end

