function ternHandles = openTernFigs()
%%OPENTERNFIGS opens the ternary diagram

%{
Copyright (c) 2016, Sally Jiao <sjiao@princeton.edu>
Copyright (c) 2016, Helge S. Stein <helge.stein@rub.de>
Copyright (c) 2016, Prof. Dr. Alfred Ludwig <alfred.ludwig@rub.de>

All rights reserved.

Redistribution and use in source and binary forms, with or without 
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, 
this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright 
notice, this list of conditions and the following disclaimer in the 
documentation and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its 
contributors may be used to endorse or promote products derived from this 
software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED 
TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR 
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; 
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR 
OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF 
ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
%}

% create tern windows
ternHandles.fTernButtons = figure(...
    'Visible', 'off', ...
    'Units', 'Normalized', ...
    'Position', [0 0.7 0.4 0.2], ...
    'Name', 'Ternary Plot Settings');
ternHandles.fTernDiagram = figure('Visible', 'off', ...
    'Units', 'Normalized', ...
    'Position', [0 0 0.45 0.45], ...
    'Name', 'Ternary Plot');

% set background to white
figure(ternHandles.fTernButtons);
set(gcf, 'color', 'w');
figure(ternHandles.fTernDiagram);
set(gcf, 'color', 'w');

% set tabs in button window
tabsTern = uitabgroup('Parent', ternHandles.fTernButtons);
tabComp = uitab('Parent', tabsTern, 'Title', 'Make cut');
tabStyle = uitab('Parent', tabsTern, 'Title', 'Plot style');
tabPostProcess = uitab('Parent', tabsTern, 'Title', 'Post-process');
tabPoint = uitab('Parent', tabsTern, 'Title', 'Point properties');
tabMatch = uitab('Parent', tabsTern, 'Title', 'Pattern matching');

%% components

% components in composition tab

leftColOffset = 0.05;
topRowOffset = 0.7;
textWidth = 0.1;
textHeight = 0.15;
textSpacingVert = 0.25;
colSpacing = 0.1;

htextConst = uicontrol('Parent', tabComp, 'Style', 'text', ...
    'String', 'Comp.', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset topRowOffset textWidth textHeight]);
htextWidth = uicontrol('Parent', tabComp, 'Style', 'text', ...
    'String', 'Width', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset (topRowOffset - textSpacingVert) ...
    textWidth textHeight]);
ternHandles.editConst = uicontrol('Parent', tabComp, 'Style', 'edit', ...
    'String', '0', ...
    'Units', 'Normalized', ...
    'Position', [(leftColOffset + colSpacing) topRowOffset ...
    textWidth textHeight], ...
    'UserData', 0, ...
    'Callback', {@editConstCallback});
ternHandles.editWidth = uicontrol('Parent', tabComp, 'Style', 'edit', ...
    'String', '0', ...
    'Units', 'Normalized', ...
    'Position', [(leftColOffset + colSpacing) ...
    (topRowOffset - textSpacingVert) ...
    textWidth textHeight], ...
    'UserData', 0, ...
    'Callback', {@editWidthCallback});

buttonColOffset = ...
    leftColOffset + textWidth + colSpacing + textWidth;
buttonWidth = textWidth;
buttonHeight = textHeight;
middleHor = 0.5 - buttonWidth / 2;

ternHandles.buttonA = uicontrol('Parent', tabComp, ...
    'Style', 'pushbutton', ...
    'String', 'A', ...
    'Units', 'Normalized', ...
    'Position', [buttonColOffset topRowOffset ...
    buttonWidth buttonHeight], ...
    'Callback', {@buttonACallback});
ternHandles.buttonB = uicontrol('Parent', tabComp, ...
    'Style', 'pushbutton', ...
    'String', 'B', ...
    'Units', 'Normalized', ...
    'Position', [buttonColOffset (topRowOffset - textSpacingVert) ...
    buttonWidth buttonHeight], ...
    'Callback', {@buttonBCallback});
ternHandles.buttonC = uicontrol('Parent', tabComp, ...
    'Style', 'pushbutton', ...
    'String', 'C', ...
    'Units', 'Normalized', ...
    'Position', [buttonColOffset ...
    (topRowOffset - textSpacingVert * 2) ...
    buttonWidth buttonHeight], ...
    'Callback', {@buttonCCallback});
ternHandles.buttonSelectPoly = uicontrol('Parent', tabComp, ...
    'Style', 'pushbutton', ...
    'String', 'Select region', ...
    'Units', 'Normalized', ...
    'Position', [buttonColOffset + buttonWidth + 0.2 (topRowOffset - textSpacingVert) ...
    0.2 buttonHeight]);

% components in style tab

buttonWidth = 0.2;
buttonHeight = textHeight;
middleHor = 0.5 - buttonWidth / 2;
topRowOffset = 0.7;
rowSpace = 0.2;
leftColOffset = 0.05;
rightColOffset = 0.6;
textWidth = 0.1;
textHeight = 0.15;

ternHandles.buttonScatter = uicontrol('Parent', tabStyle, ...
    'Style', 'pushbutton', ...
    'String', 'Scatter - XRD', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset topRowOffset ...
    buttonWidth buttonHeight], ...
    'Callback', {@buttonScatterCallback});
ternHandles.buttonSurf = uicontrol('Parent', tabStyle, ...
    'Style', 'pushbutton', ...
    'String', 'Surface - XRD', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset (topRowOffset - rowSpace) ...
    buttonWidth buttonHeight], ...
    'Callback', {@buttonSurfCallback});
ternHandles.buttonScatterEC = uicontrol('Parent', tabStyle, ...
    'Style', 'pushbutton', ...
    'String', 'Scatter - EC', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset (topRowOffset - rowSpace * 2) ...
    buttonWidth buttonHeight]);
ternHandles.buttonSurfEC = uicontrol('Parent', tabStyle, ...
    'Style', 'pushbutton', ...
    'String', 'Surface - EC', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset (topRowOffset - rowSpace * 3) ...
    buttonWidth buttonHeight]);
htextSize = uicontrol('Parent', tabStyle, ...
    'Style', 'text', ...
    'String', 'Dot size', ...
    'Units', 'Normalized', ...
    'Position', [rightColOffset topRowOffset textWidth textHeight]);
ternHandles.editSize = uicontrol('Parent', tabStyle, ...
    'Style', 'edit', ...
    'String', '30', ...
    'Units', 'Normalized', ...
    'Position', [rightColOffset (topRowOffset - rowSpace) ...
    textWidth textHeight], ...
    'UserData', 30, ...
    'Callback', {@editSizeCallback});

% components in post process tab

buttonWidth = 0.2;
buttonHeight = textHeight;
middleHor = 0.5 - buttonWidth / 2;
topRowOffset = 0.7;
rowSpace = 0.2;
leftColOffset = 0.1;
rightColOffset = 0.6;

ternHandles.buttonPoint = uicontrol('Parent', tabPostProcess, ...
    'Style', 'pushbutton', ...
    'String', 'Restore settings', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset topRowOffset ...
    buttonWidth buttonHeight], ...
    'Callback', {@buttonPointCallback});
ternHandles.buttonDelete = uicontrol('Parent', tabPostProcess, ...
    'Style', 'pushbutton', ...
    'String', 'Delete selection', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset (topRowOffset - rowSpace) ...
    buttonWidth buttonHeight], ...
    'Callback', {@buttonDeleteCallback});
ternHandles.buttonPhase = uicontrol('Parent', tabPostProcess, ...
    'Style', 'pushbutton', ...
    'String', 'Plot phases', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset (topRowOffset - rowSpace * 2) ...
    buttonWidth buttonHeight]);
ternHandles.buttonSaveAll = uicontrol('Parent', tabPostProcess, ...
    'Style', 'pushbutton', ...
    'String', 'Save analysis', ...
    'Units', 'Normalized', ...
    'Position', [rightColOffset topRowOffset ...
    buttonWidth buttonHeight], ...
    'Callback', {@buttonSaveAllCallback});
ternHandles.buttonClose = uicontrol('Parent', tabPostProcess, ...
    'Style', 'pushbutton', ...
    'String', 'Close', ...
    'Units', 'Normalized', ...
    'Position', [rightColOffset (topRowOffset - rowSpace) ...
    buttonWidth buttonHeight], ...
    'Callback', {@buttonCloseCallback});
ternHandles.buttonSaveClose = uicontrol('Parent', tabPostProcess, ...
    'Style', 'pushbutton', ...
    'String', 'Save and close', ...
    'Units', 'Normalized', ...
    'Position', [rightColOffset (topRowOffset - rowSpace * 2) ...
    buttonWidth buttonHeight], ...
    'Callback', {@buttonSaveCloseCallback});

% components in point properties tab

ternHandles.buttonXRDPlot = uicontrol('Parent', tabPoint, ...
    'Style', 'pushbutton', ...
    'String', 'XRD Plot', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset (topRowOffset - rowSpace * 0) ...
    buttonWidth buttonHeight]);

ternHandles.buttonCVPlot = uicontrol('Parent', tabPoint, ...
    'Style', 'pushbutton', ...
    'String', 'CV Log Plot', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset (topRowOffset - rowSpace * 1) ...
    buttonWidth buttonHeight]);

ternHandles.buttonCVPlotNormal = uicontrol('Parent', tabPoint, ...
    'Style', 'pushbutton', ...
    'String', 'CV Plot', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset (topRowOffset - rowSpace * 2) ...
    buttonWidth buttonHeight]);

% components in XRD matching tab

ternHandles.buttonSelectPoint = uicontrol('Parent', tabMatch, ...
    'Style', 'pushbutton', ...
    'String', 'XRD Matches (pt)', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset topRowOffset buttonWidth buttonHeight]);

ternHandles.buttonProcessAll = uicontrol('Parent', tabMatch, ...
    'Style', 'pushbutton', ...
    'String', 'XRD Matches (all)', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset (topRowOffset - rowSpace) buttonWidth buttonHeight]);

ternHandles.buttonExportMatchAll = uicontrol('Parent', tabMatch, ...
    'Style', 'pushbutton', ...
    'String', 'Export', ...
    'Units', 'Normalized', ...
    'Position', [rightColOffset (topRowOffset - rowSpace) ...
    buttonWidth buttonHeight]);

ternHandles.textConfFactor = uicontrol('Parent', tabMatch, ...
    'Style', 'text', ...
    'String', 'Conf. fact.', ...
    'Units', 'Normalized', ...
    'Position', [rightColOffset (topRowOffset - rowSpace * 0) ...
    0.2 buttonHeight]);

ternHandles.editConfFactor = uicontrol('Parent', tabMatch, ...
    'Style', 'edit', ...
    'String', '0.5', ...
    'UserData', 0.5, ...
    'Units', 'Normalized', ...
    'Position', [(rightColOffset + 0.2) (topRowOffset - rowSpace * 0) ...
    buttonWidth / 2 buttonHeight]);

ternHandles.textTol = uicontrol('Parent', tabMatch, ...
    'Style', 'text', ...
    'String', 'Tol', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset + buttonWidth + 0.02 (topRowOffset - 0 * rowSpace) ...
    0.15 buttonHeight]);

ternHandles.editTol = uicontrol('Parent', tabMatch, ...
    'Style', 'edit', ...
    'String', '0.25', ...
    'UserData', 0.25, ...
    'Units', 'Normalized', ...
    'Position', [(leftColOffset + buttonWidth + 0.14 + 0.02) (topRowOffset - 0 * rowSpace) ...
    buttonWidth / 2 buttonHeight]);

ternHandles.buttonChangeDatabaseFd = uicontrol('Parent', tabMatch, ...
    'Style', 'pushbutton', ...
    'String', 'Change DB (folder)', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset (topRowOffset - rowSpace * 2) ...
    buttonWidth buttonHeight]);

ternHandles.buttonChangeDatabaseFile = uicontrol('Parent', tabMatch, ...
    'Style', 'pushbutton', ...
    'String', 'Change DB (file)', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset (topRowOffset - rowSpace * 3) ...
    buttonWidth buttonHeight]);

ternHandles.buttonSaveDatabase = uicontrol('Parent', tabMatch, ...
    'Style', 'pushbutton', ...
    'String', 'Save DB', ...
    'Units', 'Normalized', ...
    'Position', [rightColOffset (topRowOffset - rowSpace * 3) ...
    buttonWidth buttonHeight]);

ternHandles.buttonPlotPeaks = uicontrol('Parent', tabMatch, ...
    'Style', 'pushbutton', ...
    'String', 'Plot peaks', ...
    'Units', 'Normalized', ...
    'Position', [rightColOffset (topRowOffset - rowSpace * 2) ...
    buttonWidth buttonHeight]);

%% make windows visible

fig = ternHandles.fTernButtons;
fig.Visible = 'on';
fig = ternHandles.fTernDiagram;
fig.Visible = 'on';

end
