function specHandles = openSpecFigs()
%OPENSPECFIGS opens the spec. plot window and its settings window

% create spec. windows
specHandles.fSpecButtons = figure(...
    'Visible', 'off', ...
    'Units', 'Normalized', ...
    'Position', [0.5 0.7 0.4 0.2], ...
    'Name', 'Spec. Data Plot Settings');
specHandles.fSpecPlot = figure(...
    'Visible', 'off', ...
    'Units', 'Normalized', ...
    'Position', [0.52 0.03 0.45 0.45], ...
    'Name', 'Spec. Data Plot');

% set background to white
figure(specHandles.fSpecButtons);
set(gcf, 'color', 'w');
figure(specHandles.fSpecPlot);
set(gcf, 'color', 'w');

% set tabs in button window
tabsSpec = uitabgroup('Parent', specHandles.fSpecButtons);
tabStyle = uitab('Parent', tabsSpec, 'Title', 'Plot style');
tabSelect = uitab('Parent', tabsSpec, 'Title', 'Select points');

%% components

topRowOffset = 0.7;
buttonWidth = 0.3;
buttonHeight = 0.2;
textSpacingVert = 0.2;
leftColOffset = 0.5 - buttonWidth / 2;

specHandles.buttonScaleSqrt = uicontrol('Parent', tabStyle, ...
    'Style', 'pushbutton', ...
    'String', 'Scale sq. rt.', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset topRowOffset buttonWidth buttonHeight]);
specHandles.buttonScaleLog = uicontrol('Parent', tabStyle, ...
    'Style', 'pushbutton', ...
    'String', 'Scale log', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset (topRowOffset - textSpacingVert) ...
    buttonWidth buttonHeight]);
specHandles.buttonScaleNone = uicontrol('Parent', tabStyle, ...
    'Style', 'pushbutton', ...
    'String', 'No scale', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset (topRowOffset - 2 * textSpacingVert) ...
    buttonWidth buttonHeight]);
specHandles.buttonSave = uicontrol('Parent', tabSelect, ...
    'Style', 'pushbutton', ...
    'String', 'Save points', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset topRowOffset buttonWidth buttonHeight]);

%% make windows visible

fig = specHandles.fSpecButtons;
fig.Visible = 'on';
fig = specHandles.fSpecPlot;
fig.Visible = 'on';

end

