function ECHandles = openECFigs()
%OPENECFIGS opens the EC waterfall plot window and its settings window

%{
Copyright (c) 2016, Sally Jiao <sjiao@princeton.edu>
Copyright (c) 2016, Helge S. Stein <helge.stein@rub.de>
Copyright (c) 2016, Prof. Dr. Alfred Ludwig <alfred.ludwig@rub.de>

All rights reserved.

Redistribution and use in source and binary forms, with or without 
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, 
this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright 
notice, this list of conditions and the following disclaimer in the 
documentation and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its 
contributors may be used to endorse or promote products derived from this 
software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED 
TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR 
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; 
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR 
OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF 
ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
%}

% create EC windows
ECHandles.fECButtons = figure(...
    'Visible', 'off', ...
    'Units', 'Normalized', ...
    'Position', [0.3 0.7 0.4 0.2], ...
    'Name', 'EC Data Plot Settings');
ECHandles.fECPlot = figure(...
    'Visible', 'off', ...
    'Units', 'Normalized', ...
    'Position', [0.3 0.03 0.45 0.45], ...
    'Name', 'EC Data Plot');

% set background to white
figure(ECHandles.fECButtons);
set(gcf, 'color', 'w');
figure(ECHandles.fECPlot);
set(gcf, 'color', 'w');

% set tabs in button window
tabsEC = uitabgroup('Parent', ECHandles.fECButtons);
tabStyle = uitab('Parent', tabsEC, 'Title', 'Plot style');
tabSelect = uitab('Parent', tabsEC, 'Title', 'Select plot');
tabAnalyze = uitab('Parent', tabsEC, 'Title', 'Analyze plot');
tabPostProcess = uitab('Parent', tabsEC, 'Title', 'Post-process');

%% components

topRowOffset = 0.8;
buttonWidth = 0.3;
buttonHeight = 0.2;
textSpacingVert = 0.2;
%midColOffset = 0.5 - buttonWidth / 2;
leftColOffset = 0.1;
rightColOffset = 0.5;
editHeight = buttonHeight;
editWidth = buttonWidth / 2;
rowSpace = 0.2;

% analyze tab

ECHandles.buttonLowerSlope = uicontrol('Parent', tabAnalyze, ...
    'Style', 'pushbutton', ...
    'String', 'Fit lower slope', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset topRowOffset buttonWidth buttonHeight]);
ECHandles.textLowerSlope = uicontrol('Parent', tabAnalyze, ...
    'Style', 'text', ...
    'String', '', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset (topRowOffset - rowSpace)...
    buttonWidth buttonHeight]);
ECHandles.buttonHigherSlope = uicontrol('Parent', tabAnalyze, ...
    'Style', 'pushbutton', ...
    'String', 'Fit higher slope', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset (topRowOffset - rowSpace * 2) ...
    buttonWidth buttonHeight]);
ECHandles.textHigherSlope = uicontrol('Parent', tabAnalyze, ...
    'Style', 'text', ...
    'String', '', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset (topRowOffset - rowSpace * 3) ...
    buttonWidth buttonHeight]);

ECHandles.buttonTafel = uicontrol('Parent', tabAnalyze, ...
    'Style', 'pushbutton', ...
    'String', 'Calc. Tafel slope', ...
    'Units', 'Normalized', ...
    'Position', [rightColOffset topRowOffset buttonWidth buttonHeight]);
ECHandles.textTafel = uicontrol('Parent', tabAnalyze, ...
    'Style', 'text', ...
    'String', '', ...
    'Units', 'Normalized', ...
    'Position', [rightColOffset (topRowOffset - rowSpace)...
    buttonWidth buttonHeight]);
ECHandles.buttonOnsetPot = uicontrol('Parent', tabAnalyze, ...
    'Style', 'pushbutton', ...
    'String', 'Calc. onset potential', ...
    'Units', 'Normalized', ...
    'Position', [rightColOffset (topRowOffset - rowSpace * 2) ...
    buttonWidth buttonHeight]);
ECHandles.textOnsetPot = uicontrol('Parent', tabAnalyze, ...
    'Style', 'text', ...
    'String', '', ...
    'Units', 'Normalized', ...
    'Position', [rightColOffset (topRowOffset - rowSpace * 3) ...
    buttonWidth buttonHeight]);
ECHandles.buttonReset = uicontrol('Parent', tabAnalyze, ...
    'Style', 'pushbutton', ...
    'String', 'Reset values', ...
    'Units', 'Normalized', ...
    'Position', [rightColOffset (topRowOffset - rowSpace * 4) ...
    buttonWidth buttonHeight]);

% select plot tab

ECHandles.textSelect = uicontrol('Parent', tabSelect, ...
    'Style', 'text', ...
    'String', 'Composition', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset topRowOffset buttonWidth buttonHeight]);
ECHandles.editSelect = uicontrol('Parent', tabSelect, ...
    'Style', 'edit', ...
    'String', '0', ...
    'Units', 'Normalized', ...
    'Position', [(leftColOffset + (buttonWidth - editWidth) / 2) (topRowOffset - buttonHeight + 0.05) ...
    editWidth editHeight]);
ECHandles.buttonIncrease = uicontrol('Parent', tabSelect, ...
    'Style', 'pushbutton', ...
    'String', 'Increase only', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset (topRowOffset - buttonHeight - textSpacingVert) ...
    buttonWidth buttonHeight]);
ECHandles.buttonDecrease = uicontrol('Parent', tabSelect, ...
    'Style', 'pushbutton', ...
    'String', 'Decrease only', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset (topRowOffset - buttonHeight - 2 * textSpacingVert) ...
    buttonWidth buttonHeight]);
ECHandles.buttonBoth = uicontrol('Parent', tabSelect, ...
    'Style', 'pushbutton', ...
    'String', 'Both', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset (topRowOffset - buttonHeight - 3 * textSpacingVert) ...
    buttonWidth buttonHeight]);

% style tab

ECHandles.textOffset = uicontrol('Parent', tabStyle, ...
    'Style', 'text', ...
    'String', 'Offset', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset topRowOffset buttonWidth buttonHeight], ...
    'UserData', 1);
ECHandles.editOffset = uicontrol('Parent', tabStyle, ...
    'Style', 'edit', ...
    'String', '1', ...
    'UserData', 1, ...
    'Units', 'Normalized', ...
    'Position', [(leftColOffset + (buttonWidth - editWidth) / 2) (topRowOffset - buttonHeight + 0.05) ...
    editWidth editHeight]);

% post process tab

ECHandles.buttonPrint = uicontrol('Parent', tabPostProcess, ...
    'Style', 'pushbutton', ...
    'String', 'Export Tafel/Onset data', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset topRowOffset buttonWidth buttonHeight]);

ECHandles.buttonPlotTern = uicontrol('Parent', tabPostProcess, ...
    'Style', 'pushbutton', ...
    'String', 'Plot Tafel/Onset data', ...
    'Units', 'Normalized', ...
    'Position', [leftColOffset (topRowOffset - rowSpace) ...
    buttonWidth buttonHeight]);

%% make windows visible

fig = ECHandles.fECButtons;
fig.Visible = 'on';
fig = ECHandles.fECPlot;
fig.Visible = 'on';

end

